function [C1,C2,C3,C4] = importMMAStrangeCurveData(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [C1,C2,C3,C4] = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   [C1,C2,C3,C4] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [C1,C2,C3,C4] = importfile('SCDAllBFromFit.dat',1, 400);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/20 11:50:39

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
    if nargin <= 1
        filename =...
            'C:\Users\jwt\Documents\GitHub\GQDProject\TLGAnalyticTheory\data\MMAdata\SCDAllBFromFit.dat';
    end
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
C1 = dataArray{:, 1};
C2 = dataArray{:, 2};
C3 = dataArray{:, 3};
C4 = dataArray{:, 4};

